# Oracle Linux 9
# APEX Office Print 23.1
# LibreOffice 7.4.7.2

FROM oraclelinux:9-slim
ARG email
EXPOSE 8010

RUN microdnf install -y yum && \
    yum update -y && \
    yum install -y libreoffice wget unzip tar
    
RUN	mkdir /APEXOfficePrint/ && \
    cd /APEXOfficePrint/ && \
    # wget https://s3-eu-west-1.amazonaws.com/apexofficeprint/linux/aop_linux_v23.1.zip && \
    wget http://host.docker.internal:3000/aop_linux_v23.1.zip && \
    unzip aop_linux_v23.1.zip && \
    rm aop_linux_v23.1.zip && \
    version=$(ls -d */|head -n 1) && \
    mv $version/server/* ./ && \
    rm -r $version/ && \
    chmod u+x APEXOfficePrintLinux64_4096

# RUN wget https://downloadarchive.documentfoundation.org/libreoffice/old/7.6.7.2/rpm/x86_64/LibreOffice_7.6.7.2_Linux_x86-64_rpm.tar.gz --no-check-certificate && \
RUN wget http://host.docker.internal:3000/LibreOffice_7.4.7.2_Linux_x86-64_rpm.tar.gz --no-check-certificate && \
    tar -xvf LibreOffice_7.4.7.2_Linux_x86-64_rpm.tar.gz && \
    rm LibreOffice_7.4.7.2_Linux_x86-64_rpm.tar.gz && \
    yum install -y ./LibreOffice_7.4.7.2_Linux_x86-64_rpm/RPMS/*.rpm && \
    rm -r LibreOffice_7.4.7.2_Linux_x86-64_rpm && \
    rm /usr/bin/soffice && \
    ln -s /opt/libreoffice7.4/program/soffice /usr/bin/soffice

RUN cd /APEXOfficePrint/APEXOfficePrintLinux64_4096 && ./APEXOfficePrintLinux64 -a $email
ENTRYPOINT ["/APEXOfficePrint/APEXOfficePrintLinux64_4096/APEXOfficePrintLinux64"]
